# ==================== 开关 ====================
screenshotsnap: false                    # 是否启用web截图功能
enable_github_gitee: true
enable_bilibili: true
enable_douyin: true
enable_acfun: true
enable_weibo: false
enable_nga: false
enable_xhs: false
enable_youtube: true                     # 是否启用youtube解析（建议开启）

# ==================== YouTube 专用配置 ====================
youtube_key: ""                          # ← 这里填你的 YouTube API Key
youtube_proxy: "http://192.168.0.123:2222"                        # ← 这里填代理，例如 http://127.0.0.1:7890
